ALTER TABLE employees
ADD COLUMN IF NOT EXISTS bank_holder   VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS bank_name    VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS bank_number  VARCHAR(100) NOT NULL DEFAULT '';
